### ISSUE TITLE
Raspberry PI  - ImportError: cannot import name collections_abc

### ISSUE THREAD

**Issue by pltlg** [naoki-mizuno/ds4drv#3]
Import error after running ds4drv on raspberry pi.
I also tried to build from devel source based on the given instructions 

$ git clone https://github.com/naoki-mizuno/ds4drv --branch devel
$ cd ds4drv
$ python2 setup.py install --prefix ~/.local
$ sudo cp udev/50-ds4drv.rules /etc/udev/rules.d/
$ sudo udevadm control --reload-rules
$ sudo udevadm trigger

The error after executing ds4drv:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/ds4drv", line 11, in <module>
    load_entry_point('ds4drv==0.5.1', 'console_scripts', 'ds4drv')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-aarch64/egg/ds4drv/__main__.py", line 7, in <module>
  File "build/bdist.linux-aarch64/egg/ds4drv/backends/__init__.py", line 2, in <module>
  File "build/bdist.linux-aarch64/egg/ds4drv/backends/hidraw.py", line 9, in <module>
  File "build/bdist.linux-aarch64/egg/pyudev/__init__.py", line 48, in <module>
  File "build/bdist.linux-aarch64/egg/pyudev/core.py", line 39, in <module>
  File "build/bdist.linux-aarch64/egg/pyudev/device/__init__.py", line 26, in <module>
  File "build/bdist.linux-aarch64/egg/pyudev/device/_device.py", line 37, in <module>
ImportError: cannot import name collections_abc

**Comment by pltlg** [comment]
Python issue
